language: cpp
sudo: required
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-2.0 gtk2.0
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC="gcc-7"
  - export CXX="g++-7"
  - gcc --version
  - g++ --version
script:
  - cd CHIP8-Emu
  - g++ chip8.cpp loader.cpp main.cpp vars.h `sdl2-config --cflags --libs` `pkg-config --cflags --libs gtk+-2.0`
